-- =====================================================================
-- MIGRATION v10 — EFRIS Direct S2S Integration (URA Vault)
--
-- Stores per-vendor EFRIS credentials for direct System-to-System
-- integration with URA, bypassing third-party middleware.
--
-- 1. efris_credentials — RSA keys, device numbers, TIN, status
-- 2. efris_sessions — AES key cache (per-session, 23hr TTL)
-- 3. RLS + RPCs
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. EFRIS CREDENTIALS (per-vendor vault)
-- ---------------------------------------------------------------------
create table if not exists efris_credentials (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,

  -- URA identifiers
  tin text not null,
  device_number text,                          -- assigned by URA after device registration
  brn text,                                    -- business registration number (optional)

  -- RSA key pair (PEM format — generated by edge function via Web Crypto API)
  private_key_pem text not null,               -- RSA 2048-bit private key (PKCS#8 PEM)
  public_key_pem text not null,                -- RSA 2048-bit public key (SPKI PEM)
  certificate_pem text,                        -- self-signed or CA-signed X.509 certificate

  -- Status & config
  efris_mode text not null default 'sandbox' check (efris_mode in ('sandbox','live')),
  status text not null default 'pending' check (status in ('pending','active','suspended','error')),
  last_error text,

  -- Timestamps
  registered_at timestamptz,                   -- when device was registered with URA
  last_used_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

drop trigger if exists trg_efris_credentials_updated_at on efris_credentials;
create trigger trg_efris_credentials_updated_at before update on efris_credentials
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 2. EFRIS SESSIONS (AES key cache — short-lived, per-credential)
-- ---------------------------------------------------------------------
create table if not exists efris_sessions (
  id uuid primary key default gen_random_uuid(),
  credential_id uuid not null references efris_credentials(id) on delete cascade,
  aes_key_hex text not null,                   -- hex-encoded AES-128 key
  fetched_at timestamptz not null default now(),
  expires_at timestamptz not null,             -- fetched_at + 23 hours
  is_active boolean not null default true
);

create index if not exists idx_efris_sessions_cred on efris_sessions(credential_id, is_active);

-- ---------------------------------------------------------------------
-- 3. RLS POLICIES
-- ---------------------------------------------------------------------
alter table efris_credentials enable row level security;

drop policy if exists efris_credentials_isolation on efris_credentials;
create policy efris_credentials_isolation on efris_credentials
  for all using (business_id = auth_business_id() or is_superadmin())
  with check (business_id = auth_business_id() or is_superadmin());

alter table efris_sessions enable row level security;

drop policy if exists efris_sessions_isolation on efris_sessions;
create policy efris_sessions_isolation on efris_sessions
  for all using (
    credential_id in (select id from efris_credentials where business_id = auth_business_id())
    or is_superadmin()
  )
  with check (
    credential_id in (select id from efris_credentials where business_id = auth_business_id())
    or is_superadmin()
  );

-- =====================================================================
-- END OF MIGRATION v10
-- =====================================================================
